//
//  SupportedLanguage.swift
//  wispr
//

/// Languages supported by Whisper models for transcription.
struct SupportedLanguage: Identifiable, Hashable, Sendable {
    let id: String   // ISO 639-1 code
    let name: String // Display name

    static let all: [SupportedLanguage] = [
        SupportedLanguage(id: "en", name: "English"),
        SupportedLanguage(id: "zh", name: "Chinese"),
        SupportedLanguage(id: "de", name: "German"),
        SupportedLanguage(id: "es", name: "Spanish"),
        SupportedLanguage(id: "ru", name: "Russian"),
        SupportedLanguage(id: "ko", name: "Korean"),
        SupportedLanguage(id: "fr", name: "French"),
        SupportedLanguage(id: "ja", name: "Japanese"),
        SupportedLanguage(id: "pt", name: "Portuguese"),
        SupportedLanguage(id: "tr", name: "Turkish"),
        SupportedLanguage(id: "pl", name: "Polish"),
        SupportedLanguage(id: "ca", name: "Catalan"),
        SupportedLanguage(id: "nl", name: "Dutch"),
        SupportedLanguage(id: "ar", name: "Arabic"),
        SupportedLanguage(id: "sv", name: "Swedish"),
        SupportedLanguage(id: "it", name: "Italian"),
        SupportedLanguage(id: "id", name: "Indonesian"),
        SupportedLanguage(id: "hi", name: "Hindi"),
        SupportedLanguage(id: "fi", name: "Finnish"),
        SupportedLanguage(id: "vi", name: "Vietnamese"),
        SupportedLanguage(id: "he", name: "Hebrew"),
        SupportedLanguage(id: "uk", name: "Ukrainian"),
        SupportedLanguage(id: "el", name: "Greek"),
        SupportedLanguage(id: "ms", name: "Malay"),
        SupportedLanguage(id: "cs", name: "Czech"),
        SupportedLanguage(id: "ro", name: "Romanian"),
        SupportedLanguage(id: "da", name: "Danish"),
        SupportedLanguage(id: "hu", name: "Hungarian"),
        SupportedLanguage(id: "ta", name: "Tamil"),
        SupportedLanguage(id: "no", name: "Norwegian"),
        SupportedLanguage(id: "th", name: "Thai"),
        SupportedLanguage(id: "ur", name: "Urdu"),
        SupportedLanguage(id: "hr", name: "Croatian"),
        SupportedLanguage(id: "bg", name: "Bulgarian"),
        SupportedLanguage(id: "lt", name: "Lithuanian"),
        SupportedLanguage(id: "la", name: "Latin"),
        SupportedLanguage(id: "mi", name: "Maori"),
        SupportedLanguage(id: "ml", name: "Malayalam"),
        SupportedLanguage(id: "cy", name: "Welsh"),
        SupportedLanguage(id: "sk", name: "Slovak"),
        SupportedLanguage(id: "te", name: "Telugu"),
        SupportedLanguage(id: "fa", name: "Persian"),
        SupportedLanguage(id: "lv", name: "Latvian"),
        SupportedLanguage(id: "bn", name: "Bengali"),
        SupportedLanguage(id: "sr", name: "Serbian"),
        SupportedLanguage(id: "az", name: "Azerbaijani"),
        SupportedLanguage(id: "sl", name: "Slovenian"),
        SupportedLanguage(id: "kn", name: "Kannada"),
        SupportedLanguage(id: "et", name: "Estonian"),
        SupportedLanguage(id: "mk", name: "Macedonian"),
        SupportedLanguage(id: "br", name: "Breton"),
        SupportedLanguage(id: "eu", name: "Basque"),
        SupportedLanguage(id: "is", name: "Icelandic"),
        SupportedLanguage(id: "hy", name: "Armenian"),
        SupportedLanguage(id: "ne", name: "Nepali"),
        SupportedLanguage(id: "mn", name: "Mongolian"),
        SupportedLanguage(id: "bs", name: "Bosnian"),
        SupportedLanguage(id: "kk", name: "Kazakh"),
        SupportedLanguage(id: "sq", name: "Albanian"),
        SupportedLanguage(id: "sw", name: "Swahili"),
        SupportedLanguage(id: "gl", name: "Galician"),
        SupportedLanguage(id: "mr", name: "Marathi"),
        SupportedLanguage(id: "pa", name: "Punjabi"),
        SupportedLanguage(id: "si", name: "Sinhala"),
        SupportedLanguage(id: "km", name: "Khmer"),
        SupportedLanguage(id: "sn", name: "Shona"),
        SupportedLanguage(id: "yo", name: "Yoruba"),
        SupportedLanguage(id: "so", name: "Somali"),
        SupportedLanguage(id: "af", name: "Afrikaans"),
        SupportedLanguage(id: "oc", name: "Occitan"),
        SupportedLanguage(id: "ka", name: "Georgian"),
        SupportedLanguage(id: "be", name: "Belarusian"),
        SupportedLanguage(id: "tg", name: "Tajik"),
        SupportedLanguage(id: "sd", name: "Sindhi"),
        SupportedLanguage(id: "gu", name: "Gujarati"),
        SupportedLanguage(id: "am", name: "Amharic"),
        SupportedLanguage(id: "yi", name: "Yiddish"),
        SupportedLanguage(id: "lo", name: "Lao"),
        SupportedLanguage(id: "uz", name: "Uzbek"),
        SupportedLanguage(id: "fo", name: "Faroese"),
        SupportedLanguage(id: "ht", name: "Haitian Creole"),
        SupportedLanguage(id: "ps", name: "Pashto"),
        SupportedLanguage(id: "tk", name: "Turkmen"),
        SupportedLanguage(id: "nn", name: "Nynorsk"),
        SupportedLanguage(id: "mt", name: "Maltese"),
        SupportedLanguage(id: "sa", name: "Sanskrit"),
        SupportedLanguage(id: "lb", name: "Luxembourgish"),
        SupportedLanguage(id: "my", name: "Myanmar"),
        SupportedLanguage(id: "bo", name: "Tibetan"),
        SupportedLanguage(id: "tl", name: "Tagalog"),
        SupportedLanguage(id: "mg", name: "Malagasy"),
        SupportedLanguage(id: "as", name: "Assamese"),
        SupportedLanguage(id: "tt", name: "Tatar"),
        SupportedLanguage(id: "haw", name: "Hawaiian"),
        SupportedLanguage(id: "ln", name: "Lingala"),
        SupportedLanguage(id: "ha", name: "Hausa"),
        SupportedLanguage(id: "ba", name: "Bashkir"),
        SupportedLanguage(id: "jw", name: "Javanese"),
        SupportedLanguage(id: "su", name: "Sundanese"),
    ]
}
